name: Sync upstream

on:
  schedule:
    - cron: "0 20 * * *" # 每天 UTC 20:00，北京时间 04:00；洛杉矶夏令时 13:00
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/zhiyingzzhou/renewlet.git
          git fetch upstream

      - name: Merge upstream/main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          git merge upstream/main --no-edit
          git push origin main